services:
  db:
    image: postgres:15
    container_name: test_postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user_test
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data

  app:
        build: .
        container_name: bankapi_app
        restart: always
        depends_on:
          - db
        environment:
          DATABASE_URL: postgresql+asyncpg://user_test:mypassword@db:5432/test
        ports:
          - "8000:8000"
volumes:
    postgres_data:
